#!/usr/bin/env bash
# Stage a build context (bootstrap cargo + prebuilt stage1 + ecosystem + a cargo
# config carrying the ecosystem patches) and build the fullrust toolchain image.
# Run ../build-fork.sh first so the stage1 + bootstrap cargo exist.
#
# Usage:  ./build-image.sh [minor] [tag]
#   ./build-image.sh 1.88 ghcr.io/karpeleslab/fullrust:1.88
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
MINOR="${1:-1.88}"
TAG="${2:-fullrust:$MINOR}"
BUILD="$ROOT/rust-$MINOR/build/x86_64-unknown-linux-gnu"
STAGE1="$BUILD/stage1"
CARGO="$BUILD/stage0/bin/cargo"

[[ -d "$STAGE1" ]] || { echo "missing $STAGE1 — run $ROOT/build-fork.sh first" >&2; exit 1; }
[[ -x "$CARGO"  ]] || { echo "missing bootstrap cargo $CARGO" >&2; exit 1; }

CTX="$HERE/context"
rm -rf "$CTX"; mkdir -p "$CTX"
cp -al "$STAGE1" "$CTX/stage1"                 # hardlinks: instant, no extra disk
cp -a  "$CARGO"  "$CTX/cargo"
cp -a  "$ROOT/fullrust-ecosystem" "$CTX/ecosystem"
cp -a  "$HERE/entrypoint.sh" "$CTX/entrypoint.sh"
cp -a  "$HERE/Dockerfile"    "$CTX/Dockerfile"

# Cargo config: one [patch.crates-io] entry per bundled crate, pointing at its
# in-image path. rustc + target are set via env in the Dockerfile.
{
  echo "# Ecosystem forks teaching gateway crates the fullrust target."
  echo "# Generated by build-image.sh from fullrust-ecosystem/crates/*."
  echo "[patch.crates-io]"
  for d in "$ROOT/fullrust-ecosystem/crates"/*/; do
    name="$(basename "$d")"
    echo "$name = { path = \"/opt/fullrust/ecosystem/crates/$name\" }"
  done
} > "$CTX/config.toml"

echo "== docker build $TAG =="
docker build -t "$TAG" "$CTX"
rm -rf "$CTX"
echo "== built $TAG =="
